# Generated by Django 5.2.4 on 2025-07-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_alter_variacao_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao_curta",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variavel"), ("S", "Simples")], default="V", max_length=1
            ),
        ),
    ]
