# Generated by Django 5.2.4 on 2025-07-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0004_alter_produto_descricao_curta_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
