# Generated by Django 5.2.4 on 2025-08-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="qtd_total",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
