# Generated by Django 5.2.4 on 2025-08-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_pedido_qtd_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="user",
            new_name="usuario",
        ),
    ]
