# Generated by Django 5.2.4 on 2025-08-09 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0003_rename_user_pedido_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_de_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
